---
lives: 1
starting_gems: 0
consume_turn_on_fail: false
rest_every_n_turns: 4
random_spawn_on_death:
  enabled: true
  room_id: 1 # Only used if random_spawn_on_death[:enabled] = false
lose_gems_on_death:
  enabled: true
  number: 1 # Only used if lose_gems_on_death[:enabled] = false