---
-
  name: vermillion
  teleport: false
  north:
  east: ochre
  south: aquamarine
  west:
-
  name: ochre
  teleport: false
  north: vermillion
  east: chartreuse
  south: ochre
  west:
-
  name: chartreuse
  teleport: false
  north: ochre
  east:
  south: emerald
  west:
-
  name: cobalt
  teleport: true
  north: vermillion
  east:
  south: burnt sienna
  west: vermillion
-
  name: aquamarine
  teleport: false
  north:
  east:
  south: violet
  west: cobalt
-
  name: emerald
  teleport: false
  north:
  east: lavendar
  south: burnt sienna
  west: cobalt
-
  name: lavendar
  teleport: false
  north:
  east: chartreuse
  south:
  west: burnt sienna
-
  name: violet
  teleport: false
  north:
  east: burnt sienna
  south: burnt sienna
  west: chartreuse
-
  name: burnt sienna
  teleport: false
  north: emerald
  east: lavendar
  south:
  west: